version: "3.2"
services:
  dev_apache:
    build: './www/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - /home/html/sebastian:/var/www/html
    ports:
      - "80:80"
      - "443:443"
  dev_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
networks:
  frontend:
  backend: